# Generated by Django 3.1.4 on 2021-03-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organiser',
            field=models.BooleanField(default=False),
        ),
    ]
