# Generated by Django 3.1.4 on 2021-03-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
